data:
  num_classes: 19
  ignore_label: 255
  training_size: 19132

model:
  name: minkunet
  cr: 0.5

train:
  seed: 1588147245
  deterministic: False

src_dataset:
  name: semanticAugSinglekitti
  root: /home/dataset/SemanticKITTI/sequences
  num_points: 80000
  voxel_size: 0.05

  # --- 定义 Aug 流程---
  strong_aug:
    - name: rotate_scale
      prob: 1.0
      min_angle: 0.0
      max_angle: 6.283185 # 2 * pi
      min_scale: 0.95
      max_scale: 1.05

    - name: flip_axis
      prob: 1.0
      prob_x: 0.5
      prob_y: 0.5

    - name: physical_attenuation_model
      alpha_min: 0.005
      alpha_max: 0.05
      prob: 0.5

    - name: selective_range_jittering
      mode_prob_angle: 0.5
      prob: 0.5
      jitter_dist_factor: 0.0005
      jitter_base_std: 0.01
      clip_range: [-0.05, 0.05]

    - name: intensity_channel_distortion
      prob: 0.7
      gamma_max: 1.3
      gamma_min: 0.7
      gamma_prob: 0.5

    - name: random_general_jittering
      prob: 0.2
      scale: 0.005
      max_clip: 0.01

    - name: distance_biased_point_drop
      prob: 0.2
      base_drop: 0.04
      max_drop: 0.2
      r_scale: 60.0
      gamma: 0.3
      density_voxel_size: 2.0
      protect_small_classes: [0,1,2,3,4,5,6,7, 13, 17, 18 ]
      protect_scale: 0.5

    - name: occlusion_patch
      num_patches: 1
      patch_size: 2.0
      prob: 0.1


#tgt_dataset:
#  name: semantickitti
#  root: /home/dataset/SemanticKITTI/sequences
#  num_points: 80000
#  voxel_size: 0.05

tgt_dataset:
  name: semanticstf
  root: /home/dataset/SemanticSTF
  num_points: 80000
  voxel_size: 0.05

num_epochs: 30
batch_size: 8

criterion:
  name: cross_entropy
  ignore_index: 255

optimizer:
  name: sgd
  lr: 2.4e-1
  weight_decay: 1.0e-4
  momentum: 0.9
  nesterov: true

scheduler:
  name: cosine_warmup

workers_per_gpu: 8
distributed: False
amp_enabled: True

