data:
  num_classes: 19
  ignore_label: 255
  training_size: 19132

model:
  name: minkunet_robust
  cr: 0.5
  alpha: 0.5
  lamda: 0.1
  gamma: 0.1

train:
  seed: 1588147245
  deterministic: False

src_dataset:
  name: semanticAugSinglekitti
  root: /home/dataset/SemanticKITTI/sequences
  num_points: 80000
  voxel_size: 0.05

  # --- 定义 Aug 流程---
  strong_aug:
    - name: rotate_scale
      prob: 1.0
      min_angle: 0.0
      max_angle: 6.283185 # 2 * pi
      min_scale: 0.95
      max_scale: 1.05

    - name: flip_axis
      prob: 1.0
      prob_x: 0.5
      prob_y: 0.5

    - name: physical_attenuation_model
      alpha_min: 0.005
      alpha_max: 0.05
      prob: 0.5

    - name: intensity_channel_distortion
      prob: 0.7
      gamma_max: 1.3
      gamma_min: 0.7
      gamma_prob: 0.5
    - name: nonuniform_region_perturbation
      prob: 0.5  # 触发 NRP 的概率为 0.5
      depth_selective_perturbation:
        prob: 0.5             # DSP 独立触发概率 0.5
        d_range: [20.0, 80.0] # 深度选择区间
        base_std: 0.010       # 保守的基准高斯噪声 (约 1 cm)
        dist_factor: 0.0001   # 距离因子 (使远处 sigma 缓慢增大)
      scanline_selective_perturbation:
        prob: 0.5             # SSP 独立触发概率 0.5
        num_segments: 3
        angle_width: 0.1745   # 约 10 度
        ssp_std: 0.02         # 扫描线扰动标准差 (约 2 cm)

    - name: depth_adaptive_sparsity_augmentation
      prob: 0.5  # 触发 DSA 的概率为 0.5
      depth_aware_drop:
        prob: 0.7             # D-Drop 独立触发概率 0.7 (因为这是核心退化)
        d_min: 0.5
        d_max: 100.0
        alpha: 0.4            # 最大丢弃概率系数 (40% 的最远点被丢弃)
      clustered_drop:
        prob: 0.3             # Clustered-Drop 独立触发概率 0.3 (保守)
        num_clusters: 2
        radius: 0.7           # 局部簇状丢弃半径 (保守，小于 0.8 米)
#tgt_dataset:
#  name: semantickitti
#  root: /home/dataset/SemanticKITTI/sequences
#  num_points: 80000
#  voxel_size: 0.05

tgt_dataset:
  name: semanticstf
  root: /home/dataset/SemanticSTF
  num_points: 80000
  voxel_size: 0.05

num_epochs: 50
batch_size: 8

criterion:
  name: cross_entropy
  ignore_index: 255

optimizer:
  name: sgd
  lr: 2.4e-1
  weight_decay: 1.0e-4
  momentum: 0.9
  nesterov: true

scheduler:
  name: cosine_warmup

workers_per_gpu: 8
distributed: False
amp_enabled: True

