data:
  num_classes: 19
  ignore_label: 255
  training_size: 19132

model:
  name: minkunet_dr
  cr: 0.5
  lamda_CL: 0.25   # # PointDR 对比损失权重
  lamda_SCRL: 0.1  # SCRL 损失权重
  lamda_FeatConsist: 0.3  # LDR-FR 损失权重
  repulsion_margin: 1.0  # SCRL 推远损失的 margin (L2距离)
  thing_class_ids: [ 0, 1, 2, 3, 4, 5, 6, 7, 13, 17, 18 ]

train:
  seed: 1588147245
  deterministic: False

src_dataset:
  name: semanticAugkitti
  root: /home/dataset/SemanticKITTI/sequences
  num_points: 80000
  voxel_size: 0.05

  # --- Weak Aug 流程 ---
  weak_aug:
    - name: rotate_scale         # 旋转和缩放
      prob: 1.0
      min_angle: 0.0
      max_angle: 6.283185 # 2 * pi
      min_scale: 0.95
      max_scale: 1.05


  # --- 定义 Strong Aug 流程---
  strong_aug:
    - name: rotate_scale
      prob: 1.0
      min_angle: 0.0
      max_angle: 6.283185 # 2 * pi
      min_scale: 0.95
      max_scale: 1.05

    - name: flip_axis
      prob: 1.0
      prob_x: 0.5
      prob_y: 0.5

    - name: range_dependent_jittering # 模拟折射，强度随距离增加
      prob: 0.5
      base_std: 0.01   # 近距离基础抖动 1cm
      dist_factor: 0.0005 # 每米增加 0.05cm 的 std

    - name: global_outlier_scaling # 模拟全局噪声，强度更高
      prob: 0.5
      min_ratio: 0.05 # 至少 5% 噪声
      max_ratio: 0.30 # 最高 30% 噪声（N_g / N_total = 0.30）
      intensity_scale: 1.0

    - name: vulnerable_region_drop # 启发式对抗性丢点
      prob: 0.5
      base_drop_ratio: 0.10 # 基础丢点比例
      thing_boost_factor: 2.0 # Things 区域丢点权重加倍
      remote_boost_factor: 1.5 # 远程（例如 > 40m）丢点权重增加 1.5倍
      thing_class_ids: [ 0, 1, 2, 3, 4, 5, 6, 7, 13, 17, 18 ]


#tgt_dataset:
#  name: semantickitti
#  root: /home/dataset/SemanticKITTI/sequences
#  num_points: 80000
#  voxel_size: 0.05

tgt_dataset:
  name: semanticstf
  root: /home/dataset/SemanticSTF
  num_points: 80000
  voxel_size: 0.05

num_epochs: 50
batch_size: 8

criterion:
  name: cross_entropy
  ignore_index: 255

optimizer:
  name: sgd
  lr: 2.4e-1
  weight_decay: 1.0e-4
  momentum: 0.9
  nesterov: true

scheduler:
  name: cosine_warmup

workers_per_gpu: 8
distributed: False
amp_enabled: True

